### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by sunny-kashyap** [rubenarakelyan/zomato-api-php#1]
Since we trying to fetch data from an HTTPS server there should be need to verify SSL Certificate.

So thats why it giving error of "SSL certificate problem: unable to get local issuer certificate"

So it is important that to set cURL SSL verifypeer false

use this while initializing curl code

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);

**Comment by rubenarakelyan** [comment]
Turning off this setting will allow invalid certificates as well as potential man-in-the-middle attacks to take place, which is not best practice. I recommend you update your server/PHP configuration (particularly the CA certificates) to fix the error. Please see https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/ for more information.

**Comment by sunny-kashyap** [comment]
thanks
