### ISSUE TITLE
Documentation for the API

### ISSUE THREAD

**Issue by ritz301** [rubenarakelyan/zomato-api-php#3]
As a user, I would just like to use the API rather than going through the code to learn how to use it. It would beneficial if the README could give a brief description on its usage.

**Comment by rubenarakelyan** [comment]
You can see the full API documentation at https://developers.zomato.com/documentation.

**Comment by ritz301** [comment]
Maybe I wasn't clear before. I meant the documentation of the python wrapper class you created. Like how to import it, basic parsing function syntax etc. It maybe helpful to beginners.

**Comment by rubenarakelyan** [comment]
I've added a sample file in the repository which should provide a good example of how to use the wrapper.
